Modify files
Tshepo45/Portfolio-Mobile-First pull request #2
Opened 2023-01-13 16:42 UTC by Tshepo45

fix README file typos
Modify Package.json file

2023-01-13 17:11 UTC, huseyinbiyik commented
Hi @Tshepo45,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![Alt Text](https://media.giphy.com/media/xUPGcwE3CUkXlvonug/giphy.gif)

## Invalid Code Review Request

❗️❗️ Kindly use [Microverse Readme template](https://github.com/microverseinc/readme-template) and make sure all the main sections present in yours and placeholders are replaced with your project and personal data. Please remove all the instructions targeting you. For example: "Describe how a new developer could make use of your project." The only optional section is the FAQ. Please remove the template logo on the top, if you have your own logo you can replace it with this one, otherwise please delete it. This is crucial to have a professional and instructive repository. 👌 

❗️❗️ Kindly fix your Pull Request title as requested [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md), it should have a descriptive title telling you what changes are inside. Also please fix the Pull Request description section, it should have a short summary describing the introduced changes. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-13 20:37 UTC, NahnahAJ commented
Hi @Tshepo45 , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] Please implement the changes the previous reviewer suggested you make :+1: 

1. You did job adding the README template. However, you left out some crucial parts such as 
- The Key Features Section
- The Future Features Section and 
- Lastly, the link to your MIT LICENSE file is broken. Please do well to fix all these so that the next reviewer can review your project :wink: 
2. Your PR Title and Description have still not been fixed please refer to his suggestions and fix these as well.


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-01-14 05:56 UTC, didierganthier requested changes
Hi @Tshepo45 ,

🎉 Good job so far! You're making great progress on this project, but there are still a few areas that need attention before we can move on to the next step.

<img src="https://media.giphy.com/media/cLwDB2j2a7JFdzQzYu/giphy.gif" />

## Highlights
- Descriptive PR ✔️ 
- Linters passing ✔️ 
- Correct GitHub flow ✔️ 

## Required Changes 🛠
- [ ] Please make sure all the files related to the PR are included in it, I am unable to see your `index.html` file so therefore not able to add inline comments to it. 😢 
- [ ] The container of the section should a header tag
- [ ] The logo should have a link (`a` tag).
- [ ] The hamburger button should have a `nav` tag.
  - The `nav` tag is for semantics reason, and the right position for convention and user experience for mobile devices
- [ ] The container of the section should be a `section` tag.
  -  It represents a generic standalone section of the document, so use it. [Check this link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section) for more info
- [ ] Make sure your design matches the Figma 🖼️, your toolbar lacks some padding. See below 👇🏽 
  - Your design:
![Screenshot 2023-01-14 at 00 54 25](https://user-images.githubusercontent.com/45739963/212458130-aa2573f6-c317-47a6-91b4-b75f8d26f6dd.png)
  - Figma Design:
   ![Screenshot 2023-01-14 at 00 55 28](https://user-images.githubusercontent.com/45739963/212458156-ea413f81-77ee-4fb8-ac55-7206eab28b43.png)

- Please review the comments under the review for specific changes that still need to be made.

## Optional Suggestions 💡
- While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code.

🚀 Keep pushing forward, you're almost there! If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Cheers and happy coding! 👏👏👏

2023-01-14 07:40 UTC, joskalenda requested changes
| STATUS: REQUIRED CHANGES ♻️  |
|--------------------------------|
| Hi @Tshepo45, |
|Great work on making the changes requested by a previous reviewer 👏, You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet. |
| <img src="https://media4.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif"/> |

## Highlights

- [ ]... ✅ Green linters
- [ ]... ✅ Good readme file

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 07:40 UTC, joskalenda commented on index.html
>      <div class="header">
- [ ] As the previous reviewer said, consider changing this `div` on line 14 into a `header` tag, as per the requirement, typically the header tag is used as a page header, it contains the site's title or logo (or both) and the main site navigation.

<img width="755" alt="1" src="https://user-images.githubusercontent.com/77843050/212460891-0caaf9d5-4600-47eb-8fca-73a2a51067ec.png">

- [ ] [ OPTIONAL ] This should not be an image, despite that this comment is marked as optional, I would suggest you change this into a text for more flexibility on the design

<img width="376" alt="1" src="https://user-images.githubusercontent.com/77843050/212461234-7ca24beb-fff5-4ea4-8cca-8656e1fdf644.png">

- [ ] As mentioned by the previous reviewer, you have to make a few touches on the design to match the original one, take a look at these images below and make the necessary changes, make sure your page fits the mobile screen size

### Your design ⬇️ 

<img width="352" alt="1" src="https://user-images.githubusercontent.com/77843050/212461333-47b04ce6-6195-42b0-ac99-325c5fc9bd18.png">

### Figma design ⬇️ 

<img width="390" alt="3" src="https://user-images.githubusercontent.com/77843050/212461528-20317a1c-8448-49bd-b65d-2b3cb91ab802.png">

2023-01-14 08:21 UTC, Nyame-Wolf approved these changes
# STATUS: APPROVED :heavy_check_mark: :green_circle: 

Hi @Tshepo45  :smile: , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![](https://media.giphy.com/media/l4q7TIW8nEZYOJUf6/giphy.gif)


## Highlights :sparkles:
- Made changes as requested
- Linters are passing
- Correct github flow used.

## Optional suggestions :ballot_box_with_check: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

APPROVED! 💯 💯 💯

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me, @Nyame-Wolf in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 08:21 UTC, Nyame-Wolf commented on index.html
>    <section>
[OPTIONAL] I suggest you remove the section tag here. This being the navigation, using the `section` tag and `header` tag is redundant. The `header` alone would suffice.

2023-01-14 08:38 UTC, merged